name: DEPLOY
on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: rsync deployments
              uses: burnett01/rsync-deployments@7.0.0
              with:
                  switches: -avzr --exclude=".git*" --filter="dir-merge,- .gitignore" --delete-after --progress ./ ./
                  path: /*
                  remote_path: ~/disk/wordpress/wp-content/plugins/elementor-eperi/
                  remote_host: ${{ secrets.REMOTE_HOST }}
                  remote_user: ${{ secrets.REMOTE_USER }}
                  remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
